# This is a basic workflow to help you get started with Actions

name: Continous Integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests_linux:
    strategy:
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Making virtual environment, linting
        run: |
          make testenv
          source .venv/bin/activate
          isort jaxwell/
          flake8 jaxwell/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 jaxwell/ --count --ignore=E111 --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          #mypy --allow-redefinition --config-file=pyproject.toml jaxwell/*.py

      - name: Running tests
        run: |
          source .venv/bin/activate
          coverage run --source=jaxwell -m pytest -vs
          coverage xml
          coverage html
          coverage lcov          
      - name: Upload coverage data to coveralls.io
        run: |
          source .venv/bin/activate
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: tests_linux
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
